### ISSUE TITLE
BadZipFile

### ISSUE THREAD

**Issue by CommonClimate** [nickmckay/LiPD-utilities#13]
Here is an issue submitted by my postdoc Michael Erb:

I'm having a problem opening a lipd file in python.  I installed lipd in anaconda and downloaded this file: http://wiki.linked.earth/GeoB12610-2.Rippert.2015.

In python 3, I imported lipd and tried to use the lipd.readLipd(path) command, but I'm getting an error:

reading: GeoB12610-2.Rippert.2015.lpd
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/geovault-02/erbm/programs/anaconda2/envs/py35/lib/python3.5/site-packages/lipd/__init__.py", line 49, in readLipd
    __read_file(usr_path, ".lpd")
  File "/home/geovault-02/erbm/programs/anaconda2/envs/py35/lib/python3.5/site-packages/lipd/__init__.py", line 680, in __read_file
    __universal_load(usr_path, file_type)
  File "/home/geovault-02/erbm/programs/anaconda2/envs/py35/lib/python3.5/site-packages/lipd/__init__.py", line 640, in __universal_load
    lipd_lib.read_lipd(file_meta)
  File "/home/geovault-02/erbm/programs/anaconda2/envs/py35/lib/python3.5/site-packages/lipd/pkg_resources/lipds/LiPD_Library.py", line 231, in read_lipd
    lipd_obj.read()
  File "/home/geovault-02/erbm/programs/anaconda2/envs/py35/lib/python3.5/site-packages/lipd/pkg_resources/lipds/LiPD.py", line 56, in read
    unzipper(self.name_ext, self.dir_tmp)
  File "/home/geovault-02/erbm/programs/anaconda2/envs/py35/lib/python3.5/site-packages/lipd/pkg_resources/helpers/zips.py", line 37, in unzipper
    with zipfile.ZipFile(name_ext) as f:
  File "/home/geovault-02/erbm/programs/anaconda2/envs/py35/lib/python3.5/zipfile.py", line 1026, in __init__
    self._RealGetContents()
  File "/home/geovault-02/erbm/programs/anaconda2/envs/py35/lib/python3.5/zipfile.py", line 1093, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

Any ideas?  I tried a different lipd file and got the same result.

**Comment by khider** [comment]
Did Michael take the file from the wiki?

**Comment by CommonClimate** [comment]
Yes, as the link implies.

Julien Emile-Geay, associate professor
University of Southern California
http://<https://scholar.google.com/citations?user=OVti4jEAAAAJ&hl=en>climdyn.usc.edu<http://climdyn.usc.edu>



On Jun 15, 2017, at 07:41, Deborah Khider <notifications@github.com<mailto:notifications@github.com>> wrote:


Did Michael take the file from the wiki?

**Comment by khider** [comment]
Then it's not a LiPD utilities issue. it's a wiki issue. Nick had that error a couple of times, it seems to be random. But the error needs to be reported to Varun not here.

**Comment by chrismheiser** [comment]
Yep. Wiki issue. That file doesn't even decompress after downloading.

**Comment by CommonClimate** [comment]
Ok. I'm surprised the problem hasn't been reported to Varun already, given that it was known. I'll email him.

Julien Emile-Geay, associate professor
University of Southern California
http://<https://scholar.google.com/citations?user=OVti4jEAAAAJ&hl=en>climdyn.usc.edu<http://climdyn.usc.edu>



On Jun 15, 2017, at 08:20, Deborah Khider <notifications@github.com<mailto:notifications@github.com>> wrote:


Then it's not a LiPD utilities issue. it's a wiki issue. Nick had that error a couple of times, it seems to be random. But the error needs to be reported to Varun not here.

**Comment by khider** [comment]
I did. But I don't know when he's back from vacation.

**Comment by CommonClimate** [comment]
Ok, if he's aware of the problem, that's what matters. I hope it can get fixed before OC3.

Julien Emile-Geay, associate professor
University of Southern California
http://<https://scholar.google.com/citations?user=OVti4jEAAAAJ&hl=en>climdyn.usc.edu<http://climdyn.usc.edu>



On Jun 15, 2017, at 09:34, Deborah Khider <notifications@github.com<mailto:notifications@github.com>> wrote:


I did. But I don't know when he's back from vacation.

**Comment by michaelerb** [comment]
Thanks for the replies.  I originally tried two files (http://wiki.linked.earth/GeoB12610-2.Rippert.2015 and http://wiki.linked.earth/NAm-MtLemon.Briffa.2002), and both of them gave me the error Julien posted above.  However, I just tried a third file (http://wiki.linked.earth/Eur-EasternCarpathianMountains.Popa.2008) and it works fine.  Deborah explained to me that the error might result from editing metadata on the wiki.
